#-------------------------------
# General Site Settings
title: Energy Cost Required for Mining a Single Bitcoin
logo: "logo.png"
description: y utilizing electricity consumption as a fundamental physical metric, we establish a concrete basis for evaluating Bitcoin’s intrinsic value.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://energycostmodel.com" # the base hostname & protocol for your site, e.g. http://example.com

favicon: "logo.png" 

#-------------------------------
# Author Settings
author:
  name: The Hyperlabs
  bio: Those who build on Bitcoin, sculpt the currency of the future.
  avatar: 'logo.png'

social:
- {icon: "ion-logo-linkedin", label: Linkedin, link: "https://www.linkedin.com/in/kaplanski/"}
- {icon: "ion-logo-twitter", label: Twitter, link: "https://twitter.com/Pawel_Kaplanski"}
- {icon: "ion-logo-github", label: Github, link: "https://github.com/sonofsatoshi"}
- {icon: "ion-ios-bulb", label: Patents, link: "https://patents.google.com/?q=(kaplanski+pawel)&oq=kaplanski+pawel"}
- {icon: "ion-ios-school", label: Scholar, link: "https://scholar.google.com/citations?user=Hu5Wzb0AAAAJ"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-github", label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: "Power Shift: The Rise of Thinking Electricity"
  hero__description: It’s not just electricity anymore—it’s the lifeblood of smart machines and unstoppable money. Enter the age where every spark counts for something bigger.
  hero__image: 'logo.png'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: false # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title: Get interesting news # Add your Title
mailchimp__text: Subscribe to my newsletter. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Join # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: pawel@thehyperlabs.com # Add your email for contact form
  description: You can contact us through this form. 

# NOTE
# Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: kaplanski-ai # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-S0GNR5QN6P # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jektex

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: true
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]